name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Zip Folder
      run: echo "hello to my littel mule" > My_Action.txt
    - name: Release to Github
      run: echo "Release"
